apiVersion: v1
kind: ConfigMap
metadata:
  name: pethealth-config
data:
  SERVER_PORT: "8080"

  # host.minikube.internal —  domain allows the pod to reach services on your host (Windows)
  KAFKA_BROKERS: "host.minikube.internal:9092"
  KAFKA_TOPIC: "pet_events"
  KAFKA_DLQ_TOPIC: "pet_events_dlq"
  KAFKA_CONSUMER_GROUP: "health-service-group"

  SHARD_0_MASTER_DSN: "host=host.minikube.internal user=user password=password dbname=pethealth_0 port=5432 sslmode=disable"
  SHARD_0_REPLICA_DSN: "host=host.minikube.internal user=user password=password dbname=pethealth_0 port=5432 sslmode=disable"
  SHARD_1_MASTER_DSN: "host=host.minikube.internal user=user password=password dbname=pethealth_1 port=5434 sslmode=disable"
  SHARD_1_REPLICA_DSN: "host=host.minikube.internal user=user password=password dbname=pethealth_1 port=5434 sslmode=disable"