apiVersion: apps/v1
kind: Deployment
metadata:
  name: pethealth-deployment
  labels:
    app: pethealth
spec:
  replicas: 1 # first one only, later we can scale it up
  selector:
    matchLabels:
      app: pethealth
  template:
    metadata:
      labels:
        app: pethealth
    spec:
      containers:
      - name: pethealth
        image: pethealth:v1 
        imagePullPolicy: Never # do not find image in registry, use local one
        ports:
        - containerPort: 8080
        envFrom: 
        - configMapRef:
            name: pethealth-config

        # TODO: DB и Kafka